acropolis_of_athens:
- https://www.lonelyplanet.com/greece/athens/acropolis-area/attractions/acropolis/a/poi-sig/1153952/1342281
- https://www.lonelyplanet.com/articles/a-first-time-guide-to-the-acropolis
alhambra:
- https://www.lonelyplanet.com/spain/granada/attractions/alhambra/a/poi-sig/430192/360733
- https://www.lonelyplanet.com/articles/guide-to-granada-spain
angkor_wat:
- https://www.lonelyplanet.com/articles/cambodia-famous-temple-angkor-wat-info
- https://www.lonelyplanet.com/cambodia/temples-of-angkor/attractions/angkor-wat/a/poi-sig/500516/1002179
buckingham_palace:
- https://www.lonelyplanet.com/england/london/the-west-end/attractions/buckingham-palace/a/poi-sig/370369/1321927
burj_khalifa:
- https://www.lonelyplanet.com/united-arab-emirates/dubai/downtown-dubai/attractions/burj-khalifa/a/poi-sig/1146340/1336052
chichen_itza:
- https://www.lonelyplanet.com/articles/visiting-chichen-itza-mexico
- https://www.lonelyplanet.com/mexico/eastern-yucatan-state/attractions/chichen-itza/a/poi-sig/501660/1330315
colosseum:
- https://www.lonelyplanet.com/italy/rome/ancient-rome/attractions/colosseum/a/poi-sig/1160430/1321271
- https://www.lonelyplanet.com/news/retractable-floor-colosseum
eiffel_tower:
- https://www.lonelyplanet.com/france/paris/eiffel-tower-16e-and-la-defense/attractions/eiffel-tower/a/poi-sig/372147/1322674
- https://www.lonelyplanet.com/articles/lonely-planet-guide-to-eiffel-tower
forbidden_city:
- https://www.lonelyplanet.com/china/beijing/forbidden-city-and-dongcheng-central/attractions/forbidden-city/a/poi-sig/368617/1333763
golden_gate_bridge:
- https://www.lonelyplanet.com/usa/san-francisco/the-marina-fishermans-wharf-and-the-piers/attractions/golden-gate-bridge/a/poi-sig/383417/1329639
- https://www.lonelyplanet.com/articles/15-things-you-didnt-know-about-the-golden-gate-bridge
great_barrier_reef:
- https://www.lonelyplanet.com/news/great-barrier-reef-glamping
- https://www.lonelyplanet.com/articles/guide-to-great-barrier-reef
- https://www.lonelyplanet.com/articles/sustainable-great-barrier-reef
great_pyramid_of_giza:
- https://www.lonelyplanet.com/egypt/cairo/giza-pyramids/attractions/pyramids-of-giza/a/poi-sig/1432031/1342174
- https://www.lonelyplanet.com/articles/visiting-pyramids-giza-guide-history-facts
great_wall_of_china:
- https://www.lonelyplanet.com/articles/history-of-great-wall-of-china-visit
- https://www.lonelyplanet.com/china/the-great-wall/attractions/mutianyu/a/poi-sig/1106306/356115
- https://www.lonelyplanet.com/articles/the-great-walls-most-spectacular-wild-hikes
hagia_sophia:
- https://www.lonelyplanet.com/turkey/istanbul/sultanahmet/attractions/hagia-sophia-grand-mosque/a/poi-sig/401908/1324696
- https://www.lonelyplanet.com/news/istanbul-hagia-sophia-entry-rules
- https://www.lonelyplanet.com/news/hagia-sophia-istanbul-mosque
iguaçu_falls:
- https://www.lonelyplanet.com/argentina/iguazu-falls/attractions/parque-nacional-iguazu/a/poi-sig/1146060/1006621
- https://www.lonelyplanet.com/brazil/parana/attractions/parque-nacional-do-iguacu/a/poi-sig/1266782/1314979
le_montsaintmichel:
- https://www.lonelyplanet.com/france/normandy/mont-st-michel/attractions/abbaye-du-mont-st-michel/a/poi-sig/1193158/1003102
leaning_tower_of_pisa:
- https://www.lonelyplanet.com/italy/tuscany/pisa/attractions/leaning-tower/a/poi-sig/462894/360065
- https://www.lonelyplanet.com/articles/guide-to-pisa
machu_picchu:
- https://www.lonelyplanet.com/articles/machu-picchu-facts-history-meaning-travel
- https://www.lonelyplanet.com/articles/machu-picchu-skip-crowds
mount_fuji:
- https://www.lonelyplanet.com/japan/west-of-tokyo/fuji-go-ko/attractions/mt-fuji/a/poi-sig/1309509/356827
mount_kilimanjaro:
- https://www.lonelyplanet.com/tanzania/northern-tanzania/attractions/mt-kilimanjaro-national-park/a/poi-sig/1497459/1331832
mount_rushmore:
- https://www.lonelyplanet.com/usa/south-dakota/mt-rushmore/attractions/mount-rushmore-national-memorial/a/poi-sig/469064/1324537
niagara_falls:
- https://www.lonelyplanet.com/articles/skip-niagara-falls-visit-niagara-on-the-lake
panama_canal:
- https://www.lonelyplanet.com/articles/what-to-do-on-the-panama-canal-adventure-wildlife-and-village-life
petra:
- https://www.lonelyplanet.com/jordan/petra/attractions/petra/a/poi-sig/1457302/1001785
- https://www.lonelyplanet.com/articles/responsible-travel-petra
- https://www.lonelyplanet.com/articles/essential-petra-how-to-make-the-most-of-a-one-day-visit
petronas_towers:
- https://www.lonelyplanet.com/malaysia/kuala-lumpur/bukit-bintang-klcc-pudu/attractions/petronas-towers/a/poi-sig/1151889/1336393
sagrada_família:
- https://www.lonelyplanet.com/spain/barcelona/leixample/attractions/la-sagrada-familia/a/poi-sig/374867/1320680
- https://www.lonelyplanet.com/articles/guide-to-la-sagrada-familia-barcelona
saint_peters_basilica:
- https://www.lonelyplanet.com/vatican-city/attractions/st-peter-s-basilica/a/poi-sig/1256581/1321012
- https://www.lonelyplanet.com/vatican-city/attractions/st-peter-s-basilica-dome/a/poi-sig/389941/1321012
st_basils_cathedral:
- https://www.lonelyplanet.com/russia/moscow/kremlin-kitay-gorod/attractions/st-basil-s-cathedral/a/poi-sig/373447/1336043
statue_of_liberty:
- https://www.lonelyplanet.com/usa/new-york-city/financial-district-and-lower-manhattan/attractions/statue-of-liberty/a/poi-sig/381781/1319973
- https://www.lonelyplanet.com/articles/statue-of-liberty-facts
stonehenge:
- https://www.lonelyplanet.com/england/southwest-england/stonehenge/attractions/stonehenge/a/poi-sig/1218471/359034
- https://www.lonelyplanet.com/articles/visiting-stonehenge-facts-history
- https://www.lonelyplanet.com/news/stonehenge-stones-origin
sydney_opera_house:
- https://www.lonelyplanet.com/australia/sydney/circular-quay-and-the-rocks/attractions/sydney-opera-house/a/poi-sig/367075/1322818
taj_mahal:
- https://www.lonelyplanet.com/articles/guide-to-taj-mahal
- https://www.lonelyplanet.com/india/uttar-pradesh/agra/attractions/taj-mahal/a/poi-sig/449189/356509
terracotta_army:
- https://www.lonelyplanet.com/china/shaanxi-shanxi/xian/attractions/army-of-terracotta-warriors/a/poi-sig/1016918/356065
the_great_sphinx:
- https://www.lonelyplanet.com/egypt/cairo/giza-pyramids/attractions/sphinx/a/poi-sig/406420/1342174
tower_bridge:
- https://www.lonelyplanet.com/england/london/the-city/attractions/tower-bridge/a/poi-sig/370695/1321940
uluru:
- https://www.lonelyplanet.com/articles/guide-to-uluru-kata
victoria_falls:
- https://www.lonelyplanet.com/articles/two-days-victoria-falls
